### PR TITLE
Update readme, minor changes to match leptos examples

### PR DESCRIPTION
**Pull request by ogghead**
* Updated readme to install specific version of cargo-leptos
* Minor updates to better match leptos examples

### CODE REVIEW

**Comment by ogghead** [comment]
@itowlson, I created this to address a discussion on discord :) hopefully should ensure versions align on wasm-bindgen

**Comment by itowlson** [comment]
@ogghead The README changes look great, and thanks for investigating the version stuff.  I've tested the template on Fermyon Cloud and it's still fine as far as I can tell.  Thanks!

**Comment by ogghead** [comment]
Yeah it worked for me as well there -- I don't know if the meta/style changes matters, but better to eliminate variance from the examples for sanity

**Comment by itowlson** [comment]
Bumped v2.7 and v3.0 template tags to point to the new template.

**Pull request merged**
